name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/Fribb/anime-lists.git
          git fetch upstream
          git checkout master
          git merge upstream/master -m "Merge updates from upstream"
      
      - name: Push to Fork
        run: |
          git push origin main
